
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: video_upload_app_development

test:
  <<: *default
  database: video_upload_app_test

production:
  <<: *default
  database: video_upload_app_production
  username: video_upload_app
  password: <%= ENV['VIDEO_UPLOAD_APP_DATABASE_PASSWORD'] %>
