# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26cc9b62f4ab4fabb0787f1801a863a8caaa5c622222504fbe015f42f27a72c0003c9f1b5e4eacff23a3e5fe403dd53934a8d95d863b3f380c3de702ae9a3a3

test:
  secret_key_base: 54c3ead1bb3c5e03a406b2d3a8b437e02863f7ecb50bd4a6c08c59db8ccd465153f1b3f413ebc8ab5f594eb2ec3678e1630f58456c76bde7b075b0a1008860c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
